In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\herre\OneDrive\Desktop\IT ACADEMY\PYTHON FUNDAMENTOS II\hospitals.csv",
    encoding="latin1",
    sep=";")
df.head()

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4

- 2. Realitza els exercicis de filtres següents:
- Mostra totes les dades dels hospitals que tenen entre 100 i 120 "num_camas".
- Mostra els noms dels hospitals que estan a Barcelona - Catalunya.
- Mostra els 3 hospitals amb més "indice_satisfaccion" del grup d'hospitals de Madrid i Andalusia.
- Mostra els hospitals que comencen per lletra "C" i terminen per lletra "a".

In [ ]:
df[(df['num_camas'] > 100) & (df['num_camas'] < 200)].sort_values(by='num_camas').head(5)
df[df['num_camas'].between(100,200)].sort_values(by='num_camas').head(5)

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
34,35,Hospital Royo Villanova,Zaragoza,Zaragoza,Aragon,203.83,110,229,6.2,65.2
78,79,Complejo Asistencial de Avila,Avila,Avila,Castilla y Leon,186.93,110,311,5.1,56.4
41,42,Hospital de Cabueñes,Gijon,Asturias,Asturias,100.27,111,123,9.4,91.1
136,137,Hospital General Universitario Gregorio Marañon,Madrid,Madrid,Comunidad de Madrid,487.71,112,83,8.8,64.9
98,99,Hospital de Figueres,Figueres,Girona,Cataluña,140.26,115,370,6.5,78.7

In [ ]:
df[
    (df['provincia']== 'Barcelona') &
    (df['comunidad_autonoma'] == 'Cataluña')
]['nombre']

89            Hospital Clinic de Barcelona
90                        Hospital del Mar
91    Hospital Universitario Vall d'Hebron
95    Hospital de la Santa Creu i Sant Pau
96          Hospital Municipal de Badalona
97      Hospital Universitari de Bellvitge
Name: nombre, dtype: object

In [ ]:
df[
    df['comunidad_autonoma'].isin(['Madrid','Andalucia'])
].sort_values(by='indice_satisfaccion', ascending=False).head(3)

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
17,18,Hospital Universitario de Jerez,Jerez de la Frontera,Cadiz,Andalucia,232.89,805,456,9.8,68.7
22,23,Hospital de Alta Resolucion de la Costa Occide...,Lepe,Huelva,Andalucia,261.85,304,462,9.7,50.4
25,26,Hospital Costa del Sol,Marbella,Malaga,Andalucia,248.10,610,178,9.7,51.4

In [ ]:
df[
    (df['nombre'].str.startswith('C')) &
    (df['nombre'].str.endswith('a'))
]

#df[df['nombre'].str.contains(r'^C.*a$')]
#^ → inicio
#.* → cualquier cosa
#a$ → termina en a

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
78,79,Complejo Asistencial de Avila,Avila,Avila,Castilla y Leon,186.93,110,311,5.1,56.4
81,82,Complejo Asistencial Universitario de Palencia,Palencia,Palencia,Castilla y Leon,217.95,599,189,2.3,55.8
83,84,Complejo Asistencial de Segovia,Segovia,Segovia,Castilla y Leon,206.91,610,188,8.9,76.7
87,88,Complejo Asistencial de Zamora,Zamora,Zamora,Castilla y Leon,204.16,967,126,6.7,92.5
124,125,Complejo Hospitalario Universitario de A Coruña,A Coruña,A Coruña,Galicia,149.38,791,269,5.4,84.6
153,154,Complejo Hospitalario de Navarra,Pamplona,Navarra,Navarra,142.34,450,457,8.0,74.4

- 3. Realitza els següents exercicis d'agrupacions:
- Mostra el "indice_satisfaccion" mig de cada comunitat autònoma i província de la taula "hospitals".
- Mostra el "num_camas" total de cada comunitat autònoma.
- Mostra el "porcentaje_ocupacion" més petit de cada província de cada comunitat autònoma.
- Mostra quantes províncies i localitats té cada comunitat autònoma.
- Mostra les comunitats autònomes que tenen menys de 5 hospitals.

In [ ]:
df.groupby(['comunidad_autonoma', 'provincia'])['indice_satisfaccion'].mean().round(2)
df.groupby('comunidad_autonoma')['num_camas'].sum()
df.groupby('comunidad_autonoma')['porcentaje_ocupacion'].min()
df.groupby('comunidad_autonoma').agg({
    'provincia' : 'nunique',
    'localidad' : 'nunique'
})
df.groupby('comunidad_autonoma')['hospital_id'].count()[lambda x: x < 5]

comunidad_autonoma
Cantabria    4
Ceuta        1
La Rioja     3
Melilla      1
Navarra      4
Name: hospital_id, dtype: int64

F1 - 3

Treballaràs amb un dataset de llibres més venuts a Amazon durant diversos anys. El dataset inclou informació sobre el títol del llibre, l'autor, la puntuació mitjana dels usuaris, el nombre de ressenyes, el preu, l’any de publicació i el gènere.

Carrega el csv "bestsellers with categories.csv" i realitza les següents tasques:

a. Genera dos nous datasets, un per a cada grup:
- Grup 1: Selecciona els llibres de no-ficció amb una puntuació d’usuari superior a 4.8 i un nombre de ressenyes superior a 15.000.
- Grup 2: Selecciona els llibres amb preu inferior a 10 €, publicats després de 2015 i escrits per autors que tinguin un nom que comenci per "A".

 Quants registres té cada grup?

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\herre\OneDrive\Desktop\IT ACADEMY\PYTHON FUNDAMENTOS II\bestsellers with categories.csv",encoding="latin1",
    sep=",")

df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [ ]:
df2 = df.copy()

grupo1 = df2.loc[
    (df2['Genre'] == 'Non Fiction') &
    (df2['User Rating'] > 4.8) &
    (df2['Reviews'] > 15000),
    :
]
grupo1

,Name,Author,User Rating,Reviews,Price,Year,Genre
187,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2011,Non Fiction
188,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2012,Non Fiction
189,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2013,Non Fiction
190,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2014,Non Fiction
191,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2015,Non Fiction
192,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2016,Non Fiction

In [ ]:
df3 = df.copy()

grupo2 =df3.loc[
    (df3['Price'] < 10) &
    (df3['Year'] > 2015) &
    (df3['Author'].str.lower().str.startswith('a')),
    :
]
grupo2

,Name,Author,User Rating,Reviews,Price,Year,Genre
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction
178,If Animals Kissed Good Night,Ann Whitford Paul,4.8,16643,4,2017,Fiction
179,If Animals Kissed Good Night,Ann Whitford Paul,4.8,16643,4,2019,Fiction
203,Kitchen Confidential Updated Edition: Adventur...,Anthony Bourdain,4.8,2507,8,2018,Non Fiction
232,Milk and Vine: Inspirational Quotes From Class...,Adam Gasiewski,4.4,3113,6,2017,Non Fiction
355,The Complete Ketogenic Diet for Beginners: You...,Amy Ramos,4.3,13061,6,2018,Non Fiction
356,The Complete Ketogenic Diet for Beginners: You...,Amy Ramos,4.3,13061,6,2019,Non Fiction

In [ ]:
print(f'El Grupo 1 tiene {len(grupo1)} registros')
print(f'El Grupo 2 tiene {len(grupo2)} registros')

El Grupo 1 tiene 6 registros
El Grupo 2 tiene 7 registros

b. Agrupa les dades del dataset inicial per:
    
Any de publicació i gènere, i calcula per cada grup:
- La mitjana del preu dels llibres.
- La mitjana de puntuació d’usuaris.

In [ ]:
df.groupby(['Genre', 'Year'],as_index=False)['Price'].mean()

          Genre  Year      Price
0       Fiction  2009  15.583333
1       Fiction  2010   9.700000
2       Fiction  2011  11.619048
3       Fiction  2012  12.285714
4       Fiction  2013  10.708333
5       Fiction  2014  10.172414
6       Fiction  2015   9.352941
7       Fiction  2016  12.631579
8       Fiction  2017   8.833333
9       Fiction  2018   8.761905
10      Fiction  2019   9.350000
11  Non Fiction  2009  15.230769
12  Non Fiction  2010  16.000000
13  Non Fiction  2011  17.620690
14  Non Fiction  2012  17.482759
15  Non Fiction  2013  18.192308
16  Non Fiction  2014  20.809524
17  Non Fiction  2015  10.969697
18  Non Fiction  2016  13.516129
19  Non Fiction  2017  13.730769
20  Non Fiction  2018  11.793103
21  Non Fiction  2019  10.566667

In [ ]:
df.groupby(['Genre', 'Year'],as_index=False)['User Rating'].min()

          Genre  Year  User Rating
0       Fiction  2009          4.0
1       Fiction  2010          4.1
2       Fiction  2011          4.2
3       Fiction  2012          3.3
4       Fiction  2013          3.8
5       Fiction  2014          3.9
6       Fiction  2015          3.6
7       Fiction  2016          4.0
8       Fiction  2017          4.3
9       Fiction  2018          4.3
10      Fiction  2019          4.5
11  Non Fiction  2009          4.0
12  Non Fiction  2010          4.0
13  Non Fiction  2011          4.0
14  Non Fiction  2012          4.0
15  Non Fiction  2013          4.0
16  Non Fiction  2014          4.0
17  Non Fiction  2015          4.0
18  Non Fiction  2016          4.0
19  Non Fiction  2017          4.0
20  Non Fiction  2018          4.2
21  Non Fiction  2019          4.3

c. Afegeix una nova columna anomenada "Popularitat":

- Valor "Alta" si el llibre té més de 20.000 ressenyes.
- Valor "Mitjana" si té entre 10.000 i 20.000 ressenyes.
- Valor "Baixa" si en té menys de 10.000. (0,5op)

In [ ]:
df['Popularitat'] = df['Reviews'].apply( #con lambda no necesitas el elif porque solo usa expresiones no estructuras. No bloques de codigo
    lambda x: 'Alta' if x >20000
    else 'Mitjana' if x <=10000
    else 'Baixa'
    )
df

,Name,Author,User Rating,Reviews,Price,Year,Genre,Popularitat
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,Baixa
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,Mitjana
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,Baixa
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,Alta
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,Mitjana
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,Mitjana
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,Baixa
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,Baixa
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,Baixa
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,Baixa

d. Elimina les columnes "Author" i "Year" i guarda el resultat en un nou DataFrame anomenat llibres_filtrats.

In [ ]:
df_sorter = df.drop(['Author', 'Year'], axis=1)
df_sorter

,Name,User Rating,Reviews,Price,Genre,Popularitat
0,10-Day Green Smoothie Cleanse,4.7,17350,8,Non Fiction,Baixa
1,11/22/63: A Novel,4.6,2052,22,Fiction,Mitjana
2,12 Rules for Life: An Antidote to Chaos,4.7,18979,15,Non Fiction,Baixa
3,1984 (Signet Classics),4.7,21424,6,Fiction,Alta
4,"5,000 Awesome Facts (About Everything!) (Natio...",4.8,7665,12,Non Fiction,Mitjana
...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),4.9,9413,8,Fiction,Mitjana
546,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,Non Fiction,Baixa
547,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,Non Fiction,Baixa
548,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,Non Fiction,Baixa
549,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,Non Fiction,Baixa

F1 4
En una empresa, és essencial avaluar el rendiment dels venedors per optimitzar les vendes i millorar els resultats. Un indicador clau és comparar les vendes de cada venedor amb la mitjana de l’equip comercial.

Escriu una funció que donat el dataset vendes.csv:

- Agrupi les vendes per venedor i calculi el total de cada un.
- Calculi la mitjana de vendes de tots els venedors.
- Identifiqui els venedors amb un rendiment inferior a la mitjana.
- Retorni una llista amb els noms dels venedors que han tingut vendes inferiors a la mitjana.

Crida la funció amb el dataframe vendes.csv i mostra els venedors que han tingut un rendiment en vendes per sota de la mitjana.

In [ ]:
import pandas as pd

df = pd.read_csv(r'c:\Users\herre\OneDrive\Desktop\IT ACADEMY\PYTHON FUNDAMENTOS II\vendes.csv',encoding="latin1",
    sep=";")

df = df.rename(columns={'ï»¿Venedor':'Venedor'})
df.head()

   Venedor Producte  Import
0   Carlos       TV     500
1      Ana   Laptop    1200
2   Carlos   MÃ³vil     300
3  Alberto   MÃ³vil     200
4      Ana   Tablet     700

In [ ]:
def evaluacion(dataframe):
    totales = dataframe.groupby('Venedor')['Import'].sum()
    media = totales.mean().round(2)
    resultado = totales[totales < media]
    return resultado.index.tolist() #devuelve el resultado de la función pero el index, en este caso el nombre de los vendedores
                                    # y lo convierte en lista con tolist()

In [ ]:
evaluacion(df)

['Alberto', 'Carlos', 'Laura']

3

Treballaràs amb un dataset de llibres més venuts a Amazon durant diversos anys. El dataset inclou informació sobre el títol del llibre, l'autor, la puntuació mitjana dels usuaris, el nombre de ressenyes, el preu, l’any de publicació i el gènere.

Carrega el csv "bestsellers with categories.csv" i realitza les següents tasques:

a. Genera dos nous datasets, un per a cada grup: (0,75p)
- Grup 1: Selecciona els de l'autor "Stephen King" amb una puntuació d’usuari superior o igual a 4.5 i un nombre de ressenyes superior a 3.000.
- Grup 2: Selecciona els llibres amb preu superior a 5 €, publicats abans de 2015 i escrits per autors que tinguin un nom que comenci per "H".
 Quants registres té cada grup?

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\herre\OneDrive\Desktop\IT ACADEMY\PYTHON FUNDAMENTOS II\bestsellers with categories.csv")

df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [ ]:
Grup1 = df[
    (df['Author'] == 'Stephen King') &
    (df['User Rating'] >= 4.5) &
    (df['Reviews']>3000)]

Grup1

,Name,Author,User Rating,Reviews,Price,Year,Genre
79,Doctor Sleep: A Novel,Stephen King,4.7,15845,13,2013,Fiction
194,Joyland (Hard Case Crime),Stephen King,4.5,4748,12,2013,Fiction

In [ ]:
Grup2 = df[
    (df['Price'] > 5) &
    (df['Year'] < 2015) &
    (df['Author'].str.lower().str.startswith('h'))
]

Grup2

,Name,Author,User Rating,Reviews,Price,Year,Genre
530,What to Expect When You're Expecting,Heidi Murkoff,4.4,3341,9,2011,Non Fiction

In [ ]:
print(f'El Grupo 1 tiene {len(Grup1)} registros')
print(f'El Grupo 2 tiene {len(Grup2)} registros')

El Grupo 1 tiene 2 registros
El Grupo 2 tiene 1 registros

b. Realitza els següents càlculs: (0,75p)

Agrupa les dades del dataset inicial per autor i calcula la mitjana de preu dels seus llibres

Agrupa les dades del dataset inicial any de publicació i gènere, i calcula el màxim de puntuació d'usuaris

In [ ]:
df.groupby('Author')['Price'].mean().round(2)
df.groupby(['Year','Genre'])['User Rating'].max()

Year  Genre
2009  Fiction        4.8
      Non Fiction    4.8
2010  Fiction        4.8
      Non Fiction    4.8
2011  Fiction        4.8
      Non Fiction    4.9
2012  Fiction        4.9
      Non Fiction    4.9
2013  Fiction        4.9
      Non Fiction    4.9
2014  Fiction        4.9
      Non Fiction    4.9
2015  Fiction        4.9
      Non Fiction    4.9
2016  Fiction        4.9
      Non Fiction    4.9
2017  Fiction        4.9
      Non Fiction    4.9
2018  Fiction        4.9
      Non Fiction    4.8
2019  Fiction        4.9
      Non Fiction    4.9
Name: User Rating, dtype: float64

b. Realitza els següents càlculs: (0,75p)

Agrupa les dades del dataset inicial per autor i calcula la mitjana de preu dels seus llibres

Agrupa les dades del dataset inicial any de publicació i gènere, i calcula el màxim de puntuació d'usuaris

In [ ]:
df.groupby('Author')['Price'].mean().round(2)
df.groupby(['Year','Genre'])['User Rating'].max()

Year  Genre
2009  Fiction        4.8
      Non Fiction    4.8
2010  Fiction        4.8
      Non Fiction    4.8
2011  Fiction        4.8
      Non Fiction    4.9
2012  Fiction        4.9
      Non Fiction    4.9
2013  Fiction        4.9
      Non Fiction    4.9
2014  Fiction        4.9
      Non Fiction    4.9
2015  Fiction        4.9
      Non Fiction    4.9
2016  Fiction        4.9
      Non Fiction    4.9
2017  Fiction        4.9
      Non Fiction    4.9
2018  Fiction        4.9
      Non Fiction    4.8
2019  Fiction        4.9
      Non Fiction    4.9
Name: User Rating, dtype: float64

c. Afegeix una nova columna anomenada "RangPreu":

- Valor "Car" si el preu és major a 25.
- Valor "Mig" si el preu està entre 10 i 25 (els dos preus inclosos).
- Valor "Barat" si el preu és menor a 10

In [ ]:
df['RangPreu'] = df['Price'].apply( #con lambda no necesitas el elif porque solo usa expresiones no estructuras. No bloques de codigo
    lambda x: 'Car' if x > 25
    else 'Mig' if 10<= x <= 25
    else 'Barat'
    )
df

,Name,Author,User Rating,Reviews,Price,Year,Genre,RangPreu
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,Barat
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,Mig
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,Mig
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,Barat
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,Mig
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,Barat
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,Barat
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,Barat
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,Barat
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,Barat

d. Elimina totes les columnes excepte "Name", "Author" i "Year" i guarda el resultat en un nou DataFrame anomenat llibres_filtrats.

In [ ]:
llibres_filtrats = df.loc[:,['Name','Author', 'Year']]
llibres_filtrats

,Name,Author,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,2016
1,11/22/63: A Novel,Stephen King,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018
3,1984 (Signet Classics),George Orwell,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019
...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2016
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2017
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2018
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,2019